version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "password"
      MARIADB_DATABASE: "test"
      MARIADB_USER: "user"
      MARIADB_PASSWORD: "password"

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "test"
      POSTGRES_USER: "user"